name: ui_kit
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: CinemaxIcon
      fonts:
        - asset: assets/icons/CinemaxIcon.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/montserrat_regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/montserrat_medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/montserrat_semi_bold.ttf
          weight: 600
